# Generated by Django 4.1.7 on 2023-03-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attandance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentdept', models.CharField(max_length=100)),
                ('studentbatch', models.CharField(max_length=100)),
                ('studentyear', models.DateField()),
                ('attandance', models.CharField(max_length=100)),
            ],
        ),
    ]
